# Change these first
owner: W4L33D # Your GitHub organization or username, where this repository lives
repo: DrammenURLs # The name of this repository

sites:
  - name: Drammen Kommune
    url: http://www.drammen.kommune.no
  - name: Eco Online
    url: http://www.ecoonline.no
  - name: Qudos
    url: http://www.qudos.no
  - name: Rosim
    url: http://www.rosim.no
  - name: Aasiden Skolebibliotek med ipv6
    url: https://aasbib.bib.no
    port: 200
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /DrammenURLs
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DrammenURLs
  introTitle: "Monitored URL endpoints for Drammen"
  introMessage: All endpoint monitoring enabled are shown on this webpage. URL status is updated every 5 minutes, while response time is recorded every 6 hour. The response time graph is updated once each day.
  navbar:
    - title: Status
      href: /
    - title: AzureDevops
      href: https://dev.azure.com/SopraSteria-DPSOManagedServices/RightControl

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
