# Change these first
owner: W4L33D # Your GitHub organization or username, where this repository lives
repo: DrammenURLs # The name of this repository

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 9 * * *"

sites:
  - name: Drammen Kommune
    url: http://www.drammen.kommune.no
  - name: Eco Online
    url: http://www.ecoonline.no
  - name: Qudos
    url: http://www.qudos.no
  - name: Rosim
    url: http://www.rosim.no
  - name: Aasiden Skolebibliotek
    url: https://aasbib.bib.no
    # port: 200
    # check: "tcp-ping"
    # ipv6: true
  - name: Attic
    url: https://attic-dk-vs3.icapire.net/
  - name: Børresen Skolebibliotek
    url: https://borbib.bib.no
  - name: GeoDoc
    url: https://braarkiv.no/drammen
  - name: Vegvesen- - 404
    url: https://brutus.atlas.vegvesen.no/minside
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: CarAdmin
    url: https://car.caradmin.no/
  - name: Ardoq
    url: https://d-ikt.ardoq.com
  - name: InfoCaption
    url: https://d-ikt.infocaption.com/portal/DRMK-master
  - name: Trintech
    url: https://deactx.cadency.trintech.com/
  - name: Åskollen Skolebibliotek
    url: https://dkaassk.bib.no
  - name: Aronsløkka Skolebibliotek
    url: https://dkaronsk.bib.no
  - name: Bragernes Skolebibliotek
    url: https://dkbragsk.bib.no
  - name: Brandenen Skolebibliotek
    url: https://dkbransk.bib.no
  - name: Danvik Skolebibliotek
    url: https://dkdansk.bib.no
  - name: Fjell Skolebibliotek.
    url: https://dkfjelsk.bib.no
  - name: Frydenhaug Skolebibliotek
    url: https://dkfrydsk.bib.no
  - name: Hallermoen Skolebibliotek
    url: https://dkhallsk.bib.no
  - name: Kjøsterud Skole
    url: https://dkkjosk.bib.no
  - name: Øren Skolebibliotek
    url: https://dkoresk.bib.no
  - name: Rødskog Skolebibliotek
    url: https://dkrodsk.bib.no
  - name: Skoger Skolebibliotek
    url: https://dkskogsk.bib.no
  - name: Marienlyst Skole
    url: https://dkstrosk.bib.no
  - name: Vestbygda Skolebibliotek
    url: https://dkvestsk.bib.no
  - name: ArcGIS
    url: https://drammen-kommune.maps.arcgis.com/
  - name: Drammen Extend
    url: https://drammen.extend.no/
  - name: Geminisuite
    url: https://drammen.geminisuite.com/portal/map
  - name: Quria
    url: https://drammen.quria.axiell.com/
  - name: Public 360 Online
    url: https://drammendata-ea.public360online.com/
  - name: EQS by extend
    url: https://drammenhistorisk.extend.no/
  - name: Drammen Kart
    url: https://drammenkart.nois.no/webinnsyn
  - name: Fotoware
    url: https://drammenkommune.fotoware.cloud/fotoweb
  - name: ServiceNow
    url: https://drammenkommune.service-now.com/
  - name: Asta
    url: https://drammenkommune.stiftelsen-asta.no/
  - name: Test Extend
    url: https://drammentest.extend.no/
  - name: PrintWeb
    url: https://drmk.impleoweb.no/
  - name: DriftWeb
    url: https://dw3.dk/shared/account/signin
  - name: Facilit
    url: https://fdvu.net/
  - name: Visma Flyt Sikker sak
    url: https://flyt-sikkersak-public.visma.com/
  - name: Framsikt - 404
    url: https://framiskt.net
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Galterud Skole
    url: https://gltbib.bib.no
  - name: Junglemap
    url: https://go.nanolearning.com/
  - name: Grafana Opsis
    url: https://grafana.opsis.se/
  - name: Gravekoordinering
    url: https://gravekoordinering.no/kgrav
  - name: Gulskogen Skole
    url: https://gulbib.bib.no
  - name: Norsk helsenett join nhn
    url: https://join.nhn.no/webapp2/home
  - name: Konnerud Skole
    url: https://knrbib.bib.no
  - name: CIM
    url: https://kommunecim.no/bu/drammen/
  - name: Kostrahjelp
    url: https://kostrahjelp.no/
  - name: Kundeportal Certego
    url: https://kundeportal.certego.no/login 
  - name: LCDrammen - 404
    url: https://lcdrammen.drammen.kommune.no/WE.EC.NO.Integration.Host/
    expectedStatusCodes:
      - 200
      - 201
      - 404
  - name: Mediearkiv
    url: https://mediearkiv.drammen.kommune.no/
  - name: Minlegevakt
    url: https://minlegevakt.no
  - name: Åsen skole
    url: https://neasnsk.bib.no
  - name: Eknes ungdomsskole
    url: https://neeknsk.bib.no
  - name: Killingrud ungdomsskole
    url: https://nekilsk.bib.no
  - name: Krokstad skole
    url: https://nekrosk.bib.no
  - name: Mjøndalen skolebibliotek
    url: https://nemjosk.bib.no
  - name: Solberg skolebibliotek
    url: https://nesolsk.bib.no
  - name: Stenseth skolebiblioteket
    url: https://nestensk.bib.no
  - name: Steinberg skolebibliotek
    url: https://nestesk.bib.no
  - name: Veivangen ungdomsskole bibliotek
    url: https://neveisk.bib.no
  - name: Drammen kulturskole ID porten
    url: https://nodrammen.speedadmin.dk/account/signin?&ReturnUrl=%2F&
  - name: Nye Drammen EB Public 360 online
    url: https://nyedrammen-eb.public360online.com/
  - name: Nye Drammen Public 360 online
    url: https://nyedrammen.public360online.com/
  - name: ACE Health
    url: https://openfitapi.groupnos.com/#/
  - name: Login ID porten
    url: https://passord.drammen.kommune.no
  - name: Sweco
    url: https://rosyweb.no/Login
  - name: SMP Drammen Ondni
    url: https://smpdrammen.ondni.com/
  - name: EQS by extend
    url: https://svelvikhistorisk.extend.no/
  - name: Svelvik ungdomsskole
    url: https://svkubib.bib.no
  - name: Tangen skole
    url: https://tgnbib.bib.no
  - name: Tømmerås skole
    url: https://tmrbib.bib.no
  - name: U4DK Erpexp-Drammenrdweb
    url: https://u4dk.public.cloudservices.no/Erpexp-Drammenrfdweb
  - name: Varnett
    url: https://varnett.no/portal
  - name: Varsling24
    url: https://varsling24.net/
  - name: AddSecure
    url: https://www.addsecure.no
  - name: Aktiv Kommune
    url: https://www.aktiv-kommune.no/manual-publikum/
  - name: Kursportal
    url: https://www.drmk-kursportal.no/
  - name: eDialog
    url: https://www.edialog24.no/client
  - name: Flyt Samspill
    url: https://www.individplan.no/samspill
  - name: Sticos
    url: https://www.sticos.no/logg-inn
  - name: Viascan
    url: https://www.viascan.no/
  - name: Viatraffic - 401
    url: https://www.viatraffic.com/viaservicecenter/
    expectedStatusCodes:
      - 200
      - 201
      - 404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /DrammenURLs
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DrammenURLs
  introTitle: "Monitored URL endpoints for Drammen"
  introMessage: All endpoint monitoring enabled are shown on this webpage. URL status is updated every 5 minutes, while response time is recorded every 6 hour. The response time graph is updated once each day.
  navbar:
    - title: Status
      href: /
    - title: AzureDevops
      href: https://dev.azure.com/SopraSteria-DPSOManagedServices/RightControl

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
