# Change these first
owner: W4L33D # Your GitHub organization or username, where this repository lives
repo: DrammenURLs # The name of this repository

sites:
  - name: Drammen Kommune
    url: http://www.drammen.kommune.no
  - name: Eco Online
    url: http://www.ecoonline.no
  - name: Qudos
    url: http://www.qudos.no
  - name: Rosim
    url: http://www.rosim.no
  - name: Aasiden Skolebibliotek
    url: https://aasbib.bib.no
    # port: 200
    # check: "tcp-ping"
    # ipv6: true
  - name: Attic
    url: https://attic-dk-vs3.icapire.net/
  - name: Børresen Skolebibliotek
    url: https://borbib.bib.no
  - name: GeoDoc
    url: https://braarkiv.no/drammen
  - name: Vegvesen
    url: https://brutus.atlas.vegvesen.no/minside
  - name: CarAdmin
    url: https://car.caradmin.no/
  - name: Ardoq
    url: https://d-ikt.ardoq.com
  - name: InfoCaption
    url: https://d-ikt.infocaption.com/portal/DRMK-master
  - name: Trintech
    url: https://deactx.cadency.trintech.com/
  - name: Åskollen Skolebibliotek
    url: https://dkaassk.bib.no
  - name: Aronsløkka Skolebibliotek
    url: https://dkaronsk.bib.no
  - name: Bragernes Skolebibliotek
    url: https://dkbragsk.bib.no
  - name: Brandenen Skolebibliotek
    url: https://dkbransk.bib.no
  - name: Danvik Skolebibliotek
    url: https://dkdansk.bib.no
  - name: Fjell Skolebibliotek.
    url: https://dkfjelsk.bib.no
  - name: Frydenhaug Skolebibliotek
    url: https://dkfrydsk.bib.no
  - name: Hallermoen Skolebibliotek
    url: https://dkhallsk.bib.no
  - name: Kjøsterud Skole
    url: https://dkkjosk.bib.no
  - name: Øren Skolebibliotek
    url: https://dkoresk.bib.no
  - name: Rødskog Skolebibliotek
    url: https://dkrodsk.bib.no
  - name: Skoger Skolebibliotek
    url: https://dkskogsk.bib.no
  - name: Marienlyst Skole
    url: https://dkstrosk.bib.no
  - name: Vestbygda Skolebibliotek
    url: https://dkvestsk.bib.no
  - name: ArcGIS
    url: https://drammen-kommune.maps.arcgis.com/
  - name: Drammen Extend
    url: https://drammen.extend.no/
  - name: Geminisuite
    url: https://drammen.geminisuite.com/portal/map
  - name: Quria
    url: https://drammen.quria.axiell.com/
  - name: Public 360 Online
    url: https://drammendata-ea.public360online.com/
  - name: EQS by extend
    url: https://drammenhistorisk.extend.no/
  - name: Drammen Kart
    url: https://drammenkart.nois.no/webinnsyn
  - name: Fotoware
    url: https://drammenkommune.fotoware.cloud/fotoweb
  - name: ServiceNow
    url: https://drammenkommune.service-now.com/
  - name: Asta
    url: https://drammenkommune.stiftelsen-asta.no/
  - name: Test Extend
    url: https://drammentest.extend.no/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /DrammenURLs
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DrammenURLs
  introTitle: "Monitored URL endpoints for Drammen"
  introMessage: All endpoint monitoring enabled are shown on this webpage. URL status is updated every 5 minutes, while response time is recorded every 6 hour. The response time graph is updated once each day.
  navbar:
    - title: Status
      href: /
    - title: AzureDevops
      href: https://dev.azure.com/SopraSteria-DPSOManagedServices/RightControl

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
